# Rustfmt configuration for thefuck-rs
edition = "2024"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
merge_derives = true
use_try_shorthand = true
use_field_init_shorthand = true
force_explicit_abi = true 